version: "3.8"

networks:
  omotes:
    external: true

services:
  orchestrator:
    build: ${ORCHESTRATOR_DIR}
    image: !reset

  test_worker:
    build: ${TEST_WORKER_DIR}
    deploy:
      replicas: 3
    networks:
      - omotes
    environment:
      RABBITMQ_HOSTNAME: rabbitmq-nwn
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: ${RABBITMQ_CELERY_USER_NAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_CELERY_USER_PASSWORD}
      RABBITMQ_VIRTUALHOST: omotes_celery
      LOG_LEVEL: ${LOG_LEVEL}

  integration_tests:
    build: ${INTEGRATION_TESTS_DIR}
    networks:
      - omotes
    depends_on:
      rabbitmq:
        condition: service_healthy
      omotes_influxdb:
        condition: service_healthy
      orchestrator:
        condition: service_started
    environment:
      RABBITMQ_OMOTES_USER_NAME: ${RABBITMQ_OMOTES_USER_NAME}
      RABBITMQ_OMOTES_USER_PASSWORD: ${RABBITMQ_OMOTES_USER_PASSWORD}
      RABBITMQ_VIRTUALHOST: omotes
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      LOG_LEVEL: ${LOG_LEVEL}
