"""Add job_starts table.

Revision ID: 60506a3a582f
Revises: aacf0b4d16ad
Create Date: 2024-08-27 11:08:51.629901

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "60506a3a582f"
down_revision: Union[str, None] = "aacf0b4d16ad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_starts",
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job.job_id"],
        ),
        sa.PrimaryKeyConstraint("job_id", "started_at"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("job_starts")
    # ### end Alembic commands ###
