"""esdl id in esdl_timeseries_info should be unique

Revision ID: 543bc8f6ad87
Revises: b3e9e4d8d50e
Create Date: 2025-02-13 15:44:21.484309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '543bc8f6ad87'
down_revision: Union[str, None] = 'b3e9e4d8d50e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'esdl_time_series_info', ['esdl_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'esdl_time_series_info', type_='unique')
    # ### end Alembic commands ###
